spring:
  application:
    name: slow-xmas
  datasource:
    url: jdbc:mysql://localhost:3306/slow_xmas?serverTimezone=Asia/Seoul
    username: root
    password: root12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
